/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarPaper: typeof import('@varlet/ui')['_PaperComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    VarSwitch: typeof import('@varlet/ui')['_SwitchComponent']
  }
  export interface GlobalDirectives {
    vRipple: typeof import('@varlet/ui')['_RippleComponent']
  }
}
